import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Navigation from '@/components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export default () => {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[inter.className].join(' ')}>
        <h1>Login example</h1>
        <Navigation />
      </main>
    </>
  )
}
